name: Key4hep build

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
    # - cron: '0 3 * * 6'  # 03:00 Saturday
    - cron: '0 3 * * *'  # 03:00 every day
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build_type: ["release", "nightly"]
        image: ["alma9", "ubuntu22"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: key4hep/key4hep-actions/key4hep-build@main
      with:
        build_type: ${{ matrix.build_type }}
        image: ${{ matrix.image }}
